config/routes.rb
Rails.application.routes.draw do
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  root "home#show"
  
  get 'welcome/index'
  get "/welcome" => "welcome#index"
  resources :items

end

app/models/Item.rb
class Item < ActiveRecord::Base
    self.table_name = 'salesforce.i_m__item__c'
    belongs_to :category, :primary_key => "i_m__category__c__i_m__externalid__c", :foreign_key => "i_m__externalid__c"
end

app/models/category.rb
class Category < ActiveRecord::Base
    self.table_name = 'salesforce.i_m__category__c'
    has_many :item, :primary_key => "i_m__externalid__c", :foreign_key => "i_m__category__c__i_m__externalid__c"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    session[:userinfo] = request.env['omniauth.auth']
    redirect_to '/welcome' 
  end

  def failure
    @error_msg = request.params['message']
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show

  end
end

app/controllers/items_controller.rb
class ItemsController < SecuredController
  
  def index
    @items = Item.all
  end

  def show
     @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
    @categories = Category.all
  end

  def create
    id = Time.now.to_i
    @category = Category.new(name: "Bestname #{id}", i_m__externalid__c: id)
    @category.item.build(params.require(:item).permit(:name, :i_m__description__c))
    if @category.save
        redirect_to items_path, :notice => "Cadastrado realizado com sucesso!" # usuario_path requires an id parameter like `usuario_path(@usuario)` or you could redirect to the `index` with `usuarios_path` 
    else
        render "new"
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < SecuredController
  
  def index
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth0_helper.rb
module Auth0Helper
end

app/views/home/show.html.erb
<script src="https://cdn.auth0.com/js/lock-9.1.min.js"></script>
<script>
  
  var lock = new Auth0Lock('OaaRzsLcJSodX1LoyCLLkaMaKSwGpxkC', 'app52272635.auth0.com');
  
  
  function signin() {
    lock.show({
        callbackURL: "<%= ENV['AUTH0_CALLBACK_URL'] %>"
      , responseType: 'code'
      , authParams: {
        scope: 'openid email'
      }
    });
  }

  $(document).ready(function(){window.signin()})  
  
</script>

app/views/items/index.html.erb
<h1>Salesforce Items</h1>
<table>
    <tr>
        <th>Name</th><th>Description</th><th>Salesforce Id</th>
    </tr>
    <% @items.each do |item| %>
    <tr>
        <td><%= item.name %>
        <td><%= item.i_m__description__c %>
        <td><%= item.sfid %></td>
        <td><%= link_to 'Show', item_path(item) %></td>
    </tr>
    <% end %>
</table>


<p><%= link_to "Add new item", {:action => 'new' }%></p>

app/views/items/new.html.erb
<%= form_for @item, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :i_m__description__c %>
  <%= f.select 'i_m__to_category__c', options_for_select(@categories.map{|category| ["#{category.name}", category.sfid] }) %>
  <%= f.submit "Create" %>
<% end %>

app/views/items/show.html.erb
<h1>Salesforce Item: <%= @item.name %></h1>

</br>
</br>

<h4><%= @item.name %></h4>
<h4><%= @item.i_m__description__c %></h4>
<h4><%= @item.sfid %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to the secret base of operation</h1>

<%= link_to "Review avaliable resources", { :controller => :items, :action => :index } %>